### ISSUE TITLE
Issue w/ chrome web store posting

### ISSUE THREAD

**Issue by Chaprnks** [bernardodsanderson/material-neutron#1]
![3XVOJs](https://user-images.githubusercontent.com/6340970/112737375-80616200-8f30-11eb-8b8a-8f858676248d.png)

**Comment by Explosion-Scratch** [comment]
Same here

**Comment by kelbazz** [comment]
yeah why ?

**Comment by bernardodsanderson** [comment]
Chrome apps are officially gone: https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html
